// export const LANDING = '/'
// export const BUSINESS = '/business'
// export const EXPLORE = '/explore'
// export const LANGUAGE = '/language'
// export const CURRENCY_TYPE = '/currency-type'
// export const SELLER = '/seller'
// export const SIGN_UP = '/sign-up'
// export const SIGN_IN = '/sign-in'

export const LANDING = ''
export const BUSINESS = ''
export const EXPLORE = ''
export const LANGUAGE = ''
export const CURRENCY_TYPE = ''
export const SELLER = ''
export const SIGN_UP = ''
export const SIGN_IN = ''

export const ABOUTUS = ''
export const FEATURES = ''
export const HOWITWORKS = ''
export const FAQ = ''
export const CONTACT = ''
export const SHOPPING = ''
